# @TODO Replace all `<CODE_DIR>` with the path to the source code.
# docker-elabftw configuration file
# use : "docker-compose up -d" to start containers
# https://hub.docker.com/r/elabftw/elabimg/
# https://www.elabftw.net

# our first container is nginx + php-fpm + elabftw
web:
    image: elabftw/elabimg:dev
    restart: always
    container_name: surveyo-web
    # drop some capabilities
    cap_drop:
        - SYS_ADMIN
        - AUDIT_WRITE
        - MKNOD
        - SYS_CHROOT
        - SETFCAP
        - NET_RAW
        - SYS_PTRACE
    environment:
        # MySQL config (see also the `surveyo-mysql` container)
        - DB_HOST=mysql
        - DB_NAME=surveyo
        - DB_USER=surveyo
        - DB_PASSWORD=  # @TODO Define this. Must be the same as `surveyo-mysql.MYSQL_PASSWORD`.

        # get your secret key from https://demo.elabftw.net/install/generateSecretKey.php
        # if you don't want to get it from an external source you can also do that:
        # docker run -t --entrypoint '/bin/sh' elabftw/elabimg -c "php /elabftw/install/generateSecretKey.php"
        - SECRET_KEY=  # @TODO Define this. Read comments here above.

        # optional: change to your server name in nginx config
        - SERVER_NAME=localhost
        # optional: disable https, use this to have an http server listening on port 443
        # useful if the SSL stack is handled by haproxy or something alike
        - DISABLE_HTTPS=false
        # set to true to use letsencrypt certificates
        # note: does nothing if DISABLE_HTTPS is set to true
        - ENABLE_LETSENCRYPT=false
        # no need to change
        - MAX_PHP_MEMORY=256M
        # no need to change
        - MAX_UPLOAD_SIZE=100M
        # better if changed (see list of available values: http://php.net/manual/en/timezones.php
        - PHP_TIMEZONE=Europe/Brussels
    ports:
        # if you want elabftw to run on a different port, change the first number
        # host:container
        - "443:443"
    volumes:
        # path to elabftw source code
        - <CODE_DIR>/src:/elabftw
        # this is where you will keep the uploaded files persistently
        # remark: must be below the webroot, so not in /var
        # host:container
        - <CODE_DIR>/var/uploads:/surveyo/uploads
        # if you've enabled letsencrypt, uncomment the line below
        # path to the folder with SSL certificates (must contain fullchain.pem and privkey.pem)
        # host:container
        - <CODE_DIR>/var/ssl:/ssl

    links:
        - mysql
mysql:
    image: mysql:5.7
    restart: always
    container_name: surveyo-mysql
    # drop some capabilities
    cap_drop:
        - AUDIT_WRITE
        - MKNOD
        - SYS_CHROOT
        - SETFCAP
        - NET_RAW
    environment:
        # MySQL config (see also the `surveyo-web` container)
        - MYSQL_ROOT_PASSWORD=  # @TODO Define this.
        - MYSQL_DATABASE=surveyo
        - MYSQL_USER=surveyo
        - MYSQL_PASSWORD=  # @TODO Define this. Must be the same as `surveyo-web.DB_PASSWORD`.

    volumes:
        # this is where you will keep the database persistently
        # host:container
        - <CODE_DIR>/var/mysql:/var/lib/mysql
